version: "3"
services:
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - TRANSMISSION_WEB_HOME=/combustion-release/ #optional
    volumes:
      - /home/t4ks/go/src/github.com/teror4uks/gobot/tr_config:/config
      - /home/t4ks/go/src/github.com/teror4uks/gobot/tr_downloads:/downloads
      - /home/t4ks/go/src/github.com/teror4uks/gobot/tr_watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
